### ISSUE TITLE
SparseBox crash on open

### ISSUE THREAD

**Issue by xoshhh** [khanhduytran0/SparseBox#16]
Having it crash when I first start it. Haven't gotten into it at all. Tried on 18.0.1 and 17.7, closed SideStore before openinig it. I have followed everything normal and then it still doesnt work. Reinstalled everything, turned of find my, restarted my phone... idk I just want it to work :(

**Comment by khanhduytran0** [comment]
Please go to analytics logs and send SparseBox crash report.

**Comment by xoshhh** [comment]
(https://drive.google.com/file/d/1CkkZU_a9i8r9_Z-G62BIaF0b-wpAz-OF/view?usp=sharing)](https://drive.google.com/file/d/1CkkZU_a9i8r9_Z-G62BIaF0b-wpAz-OF/view?usp=sharing)

It said the file type wasnt supported so this is what I got. I don't know much about the logs but on the top it says iPhone 12 when I have an 11? Does that matter? Thanks for the response

**Comment by khanhduytran0** [comment]
Please try latest build and let me know if anything changes.

**Comment by hesier** [comment]
[SparseBox-2024-10-12-221018.ips.txt](https://github.com/user-attachments/files/17350373/SparseBox-2024-10-12-221018.ips.txt)

I tried using the latest build version, but it still crashes.

**Comment by xoshhh** [comment]
Sam here

**Comment by reeza88** [comment]
same sparsebox won't open after sidestore using 0.5.3 MDC. already closed sidestore and clicked aparsebox but crashed. ip 15 pro max iOS 17.5.1

**Comment by xoshhh** [comment]
Anyone here with this issue figure it out?

**Comment by TEKHD** [comment]
Same here... It simply won't open. iPhone 16 Pro Max IOS 18.0.1

**Comment by reeza88** [comment]
found solution. regenerate mobilegestalt reset through misakax then install sparsebox through side store again

**Comment by xoshhh** [comment]
@reeza88 Never used misakax though?

**Comment by WongIong** [comment]
11PM 17.5.1, crash at first lauch and forever.

**Comment by reeza88** [comment]
> 11PM 17.5.1, crash at first lauch and forever.

Make sure use sidestore mdc version 0.5.3.

**Comment by hesier** [comment]
> 11PM 17.5.1, crash at first lauch and forever.

我在电脑上使用 misakax 点击 `regenerate mobilegestalt reset` 后，再重新安装 sparsebox 就可以了，记得使用 action 版本的 sidestore 

I used misakax on PC and clicked `regenerate mobilegestalt reset`. After that, I reinstalled sparsebox and it worked. Remember to use the action version of sidestore.

https://github.com/SideStore/SideStore/actions/runs/11661089461/artifacts/2139872659

> found solution. regenerate mobilegestalt reset through misakax then install sparsebox through side store again
