### ISSUE TITLE
iPadOS enable problem

### ISSUE THREAD

**Issue by silihoa2k7** [khanhduytran0/SparseBox#18]
![IMG_5319](https://github.com/user-attachments/assets/a15cf03c-8af2-4695-a235-6305a13427aa)

**Comment by silihoa2k7** [comment]
i downloaded the last version in Actions

**Comment by silihoa2k7** [comment]
i restart device and its just enable 
![IMG_5321](https://github.com/user-attachments/assets/fc2b7af1-e1a7-4aa9-9f1e-01c500b4759f)

**Comment by silihoa2k7** [comment]
and my standby mode is gone :((

**Comment by khanhduytran0** [comment]
Try latest build, it should work
