### ISSUE TITLE
iPadOS error

### ISSUE THREAD

**Issue by da-vinci-noob** [khanhduytran0/SparseBox#19]
iPhone 13 Pro Max. ios 17.0
Restore Failed then in end it says restore success.
![IMG_0167](https://github.com/user-attachments/assets/d1e575af-d3e7-4b21-9ae9-68357bde2039)

I got the settings, but nothing enables. Stage Manager, Swipe from bottom left/right.

![IMG_0169](https://github.com/user-attachments/assets/893cd91a-4482-46ba-95ed-240796e1a5d7)

![IMG_0168](https://github.com/user-attachments/assets/3a89db9f-3c4e-417f-8bdb-690105bfff0d)

**Comment by silihoa2k7** [comment]
same with me

**Comment by da-vinci-noob** [comment]
@khanhduytran0 - Yes, it works fine now.
But I cannot use WhatsApp now as it now detects as iPadOS, is there any way I can bypass that.?
Or if there is any way I can use the iPad Dock (Floating Dock) without the whole iPadOS function.?

**Comment by AnUnkn0wnGithubUser** [comment]
> Latest build should work Also important: never disable show dock when using stage manager, it could cause respring loop

it's not working for me, can you tell me which one i should use?

**Comment by AnUnkn0wnGithubUser** [comment]
> @khanhduytran0 - Yes, it works fine now. But I cannot use WhatsApp now as it now detects as iPadOS, is there any way I can bypass that.? Or if there is any way I can use the iPad Dock (Floating Dock) without the whole iPadOS function.?

it's not working for me, can you tell me which one i should use?

**Comment by da-vinci-noob** [comment]
> 
> 
> > @khanhduytran0 - Yes, it works fine now. But I cannot use WhatsApp now as it now detects as iPadOS, is there any way I can bypass that.? Or if there is any way I can use the iPad Dock (Floating Dock) without the whole iPadOS function.?
> 
> 
> 
> it's not working for me, can you tell me which one i should use?

Download Latest build artifact from actions.

https://github.com/khanhduytran0/SparseBox/actions/runs/11305765003
