### ISSUE TITLE
After restoring, nothing seems to change

### ISSUE THREAD

**Issue by pengubow** [khanhduytran0/SparseBox#2]
After restoring, nothing seems to change. I enabled AOD, but it doesn't seem to work.

**Comment by pengubow** [comment]
![IMG_0062](https://github.com/user-attachments/assets/a6b84d3c-2bd8-4c36-abf0-83cde2f8e9f8)

**Comment by pengubow** [comment]
^^ if i disable rebooting after a restore

**Comment by JustAiden9** [comment]
Exact same issue for some reason. The restore works like normal, but none of the tweaks actually apply...

**Comment by JustAiden9** [comment]
I am on iPhone 14 18rc btw

**Comment by khanhduytran0** [comment]
I made some mistakes writing backup commands, I’m working on fix

**Comment by JustAiden9** [comment]
Ok sounds good!

**Comment by JustAiden9** [comment]
561bb92 still did not fix it for me

**Comment by JustAiden9** [comment]
LOG FILE:
11:00:40 [TRACE] minimuxer::muxer: Handling ListDevices
Executing args: ["idevicebackup2", "-n", "restore", "--no-reboot", "--system", "/var/mobile/Containers/Data/Application/4FDCD764-4921-4722-92CD-1A19B8D63973/Documents/"]
11:00:40 [TRACE] minimuxer::muxer: Handling ListDevices
Backup directory is "/var/mobile/Containers/Data/Application/4FDCD764-4921-4722-92CD-1A19B8D63973/Documents/"
11:00:40 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:40 [TRACE] minimuxer::muxer: Handling ReadBUID
11:00:40 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
Started "com.apple.mobilebackup2" service on port 50417.
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
Negotiated Protocol Version 2.1
Reading Info.plist from backup.
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadBUID
11:00:41 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadBUID
11:00:41 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadBUID
11:00:41 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:41 [TRACE] minimuxer::muxer: Handling ReadPairRecord
Starting Restore...
Restoring system files: Yes
Rebooting after restore: No
Don't copy backup: Yes
Preserve settings of device: Yes
Remove items that are not restored: No
Backup password: No
No Applications in Info.plist, skipping creation of RestoreApplications.plist
Wrote RestoreApplications.plist
Sending '00008110-001E09280246401E/Status.plist' (488 Bytes)
Sending '00008110-001E09280246401E/Manifest.plist' (2.2 KB)
Sending '00008110-001E09280246401E/Manifest.mbdb' (367 Bytes)
Sending '00008110-001E09280246401E/Info.plist' (181 Bytes)
Sending '00008110-001E09280246401E/5d4fb285a3a8c4349cd1672bb6551066383db4df' (0 Bytes)
Sending '00008110-001E09280246401E/d9d5357af48079ffd6828954cd3915b0266ad2f1' (14.5 KB)

[==================================================] 100% Finished
ErrorCode 18: _restoreRegularFiles:size: rename error: Cross-device link (18) at path "/private/var/.backup.i/var/root/Library/Backup/SystemContainers/Data/../../../../../../../../crash_on_purpose" (MBErrorDomain/18)
Restore Failed (Error Code 18).
11:00:42 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:42 [TRACE] minimuxer::muxer: Handling ReadBUID
11:00:42 [TRACE] minimuxer::muxer: handle_packet error: UnknownMessageType
11:00:42 [TRACE] minimuxer::muxer: Handling ReadPairRecord
11:00:42 [TRACE] minimuxer::muxer: Handling ReadPairRecord

**Comment by JustAiden9** [comment]
Latest commit

**Comment by JustAiden9** [comment]
Ok AOD just worked I dont really understand why it did though

**Comment by JustAiden9** [comment]
So I think it works to a point

**Comment by JustAiden9** [comment]
I think they need to add the fix that Nugget uses to allow 18rc to have all the mobilegestalt tweaks back

**Comment by JustAiden9** [comment]
Hmm, I still can’t seem to get it working on iOS 18rc the only thing that sort of works is AOD. Did you add the thing Lemin added to make 18rc work for nugget yet?

**Comment by pengubow** [comment]
It works now!

**Comment by khanhduytran0** [comment]
@pengubow are you on 18.0rc or older?

**Comment by pengubow** [comment]
I’m on RC, yes

**Comment by pengubow** [comment]
Well, maybe it was just a fluke. When I’m on WiFi ima try something else, other than Action Button.

![IMG_0063](https://github.com/user-attachments/assets/22c685aa-19f9-48a7-abf3-7ae74c7c4f2c)

**Comment by pengubow** [comment]
It works, but only if I disable reboot after restore.

**Comment by pengubow** [comment]
^^

**Comment by pengubow** [comment]
just tried again without reboot, even though it exits still with error code -18, it seems to work.
