### ISSUE TITLE
错误代码211

### ISSUE THREAD

**Issue by ljfwmg3890** [khanhduytran0/SparseBox#26]
iphone 14pro 17.2

**Comment by ljfwmg3890** [comment]
![IMG_6900](https://github.com/user-attachments/assets/af8406f3-fafb-4b97-9a41-e085fe7941f6)

**Comment by ljfwmg3890** [comment]
![Uploading IMG_6901.png…]()

**Comment by ljfwmg3890** [comment]
![Uploading IMG_6901.png…]()

**Comment by 136478738** [comment]
关闭查找

**Comment by ljfwmg3890** [comment]
> 关闭查找

是的，已解决了
