### ISSUE TITLE
SparseBox crashing on launch iOS 18.0.1

### ISSUE THREAD

**Issue by MatchStickMobRockect** [khanhduytran0/SparseBox#32]
^^^

**Comment by MatchStickMobRockect** [comment]
> close sidestore

Didnt work

**Comment by MatchStickMobRockect** [comment]
I even downgraded to ios 17.7 and the app wss still crashing then i ota delayed to 18.0 and still the same issue.

**Comment by MatchStickMobRockect** [comment]
> > I even downgraded to ios 17.7 and the app wss still crashing then i ota delayed to 18.0 and still the same issue.
> 
> Can you open the issue on Discord?

could you please give me the link of the server?Thank you.

**Comment by sdgros01** [comment]
Yeah what’s discord link because I’m running into multiple issues trying to get iPad mode to work on iPhone

**Comment by reeza88** [comment]
found solution. regenerate mobilegestalt reset through misakax install sparsebox through side store again
