### ISSUE TITLE
minimuxer.MinimuxerError 0 when trying to sideload a 5th app on sidestore

### ISSUE THREAD

**Issue by snowlandgit** [khanhduytran0/SparseBox#36]
![IMG_0136](https://github.com/user-attachments/assets/f2a64e40-3379-4563-a6b7-bc388b63bb37)
![IMG_0137](https://github.com/user-attachments/assets/2232c00b-b51f-4804-a6a5-2e0996729bf6)

**Comment by luh-99** [comment]
Sorry for late reply, go to anisette servers and click Macley
