### ISSUE TITLE
file picker

### ISSUE THREAD

**Issue by pengubow** [khanhduytran0/SparseBox#4]
When sideloaded with dev/enterprise cert, then the file picker doesn’t pick files.

**Comment by khanhduytran0** [comment]
I have implemented a workaround that lets you drag-and-drop file instead, let me know if it works.

**Comment by pengubow** [comment]
Where can I drop it though?

**Comment by khanhduytran0** [comment]
Drop it on `select pairing file` button

**Comment by pengubow** [comment]
can’t drop there

**Comment by pengubow** [comment]
![IMG_0070](https://github.com/user-attachments/assets/09e3f892-bb7a-497a-8731-21c6b67f9120)

**Comment by pengubow** [comment]
@khanhduytran0 ^^
