### ISSUE TITLE
Bypass 3 apps limit not working with iPadOS 17.4.1 and iPad Pro M2

### ISSUE THREAD

**Issue by corysus** [khanhduytran0/SparseBox#51]
Hi, I didn't find anywhere more information about this problem, so I will ask here.

I try to use SparseBox to bypass the 3-app limit with SideStore, but for some reason this does not work. I always get error -205 (pictures below). I am using the latest version of SparseBox and the latest SideStore nightly build with the "Disable App Limit" option checked on.

Picture 1:
![IMG_0380](https://github.com/user-attachments/assets/b284a88a-17f6-4037-8012-f9489831431d)

Also, sometimes I get this, but again I can't install more than 3 apps with SideStore.
![IMG_0380](https://github.com/user-attachments/assets/6e5e7fea-0f56-4775-938f-f7d0478238de)

Does this work with M chips anyway?

**Comment by corysus** [comment]
Yes, I have a lot of apps (I use my iPad as laptop replacement), and I also use dev certs, but only for a few apps, mostly for Fortnite and emulators. I also use your LiveContainer because these days, using certificates is not safe and they get revoked very often.

Currently, I don't have 200GB of free space on my Mac to create a backup and send you `Manifest.mbdb`. Is there any other workaround that I can try?

**Comment by khanhduytran0** [comment]
I didn’t meant to get your backup’s `Manifest.mbdb`, but the one generated by SparseBox, you can find it in Files app.

**Comment by corysus** [comment]
Ah, here is: 
[Manifest.mbdb.zip](https://github.com/user-attachments/files/17731915/Manifest.mbdb.zip)

**Comment by corysus** [comment]
Do you need some more information? I attached the manifest from SparseBox.

**Comment by corysus** [comment]
@khanhduytran0 Is there any solution for this?

**Comment by khanhduytran0** [comment]
Looks like an app having non-ASCII character (`Device Monitor².app`) on the bundle name broke it. Fix coming.
