### ISSUE TITLE
succeed ! activate more than 3 apps

### ISSUE THREAD

**Issue by ljfwmg3890** [khanhduytran0/SparseBox#60]
14pro  17.2

**Comment by ljfwmg3890** [comment]
![IMG_7683](https://github.com/user-attachments/assets/d575ced1-4266-4ec2-b2ee-f71947db323a)

**Comment by ljfwmg3890** [comment]
![IMG_7684](https://github.com/user-attachments/assets/ac02e306-c190-4ebc-9df6-e2be72858cbd)

**Comment by quuuut** [comment]
this is an issues tab, not a success tab
