### ISSUE TITLE
Sparsebox crash

### ISSUE THREAD

**Issue by Graysonmee2006** [khanhduytran0/SparseBox#62]
So i was used to open sparsebox but it crashed, my ios ver at the momment is ios 18.0.1, i turned on the sidestore vpn and closed the sidestore app too, i even reseted the mobilegesalt file using nugget but i still crashed, anyway to fix?

**Comment by omegion3** [comment]
just restart your ipad/iphone, i have the same one before.

**Comment by omegion3** [comment]
i have a same thing as you are, depends if i restart my ios, it still crash (even if i'm on the beta version)

**Comment by Infinitay** [comment]
Lately I've been having some random crashes too, but it usually fixes itself and I can open it back up. Not sure what the issue was.
