### ISSUE TITLE
to ios18.2 b2 support bypassing the 3 apps loaded limit

### ISSUE THREAD

**Issue by Fivens** [khanhduytran0/SparseBox#67]
Wondering if versions prior to ios18.2 b2 support bypassing the 3 apps loaded limit, I've searched a lot of places that don't explicitly state that, except to see that the vulnerability wasn't fully patched after iOS18.1 b4. It wasn't fully blocked until 18.2 b2

**Comment by Br0des** [comment]
I’m on 18.2 b2 😭

**Comment by khanhduytran0** [comment]
Unfortunately, when it was patched, what was left was just too limited to be usable for 3 app limit bypass.
